region          = "ap-northeast-2"
vpc_id          = "<vpc_id>" 
subnet_id       = "<subnet_id>"
name            = "flask-aws-iam-checker"
instance_type   = "t3.large"
key_pair_name   = "<key_pair_name>" 
