apiVersion: v1
kind: Service
metadata:
  name: aws-iam-checker-service
spec:
  type: NodePort
  selector:
    app: aws-iam-checker
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
